default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: water_development
  host: localhost
  username: water
  password: ys321artem

test:
  <<: *default
  database: water_test
  host: localhost
  username: water
  password: ys321artem

production:
  <<: *default
  database: water_production
  username: water
  password: <%= ENV['WATER_DATABASE_PASSWORD'] %>
